### ISSUE TITLE
netgen 6.2.2004

### ISSUE THREAD

**Issue by looooo** [trelau/SMESH#20]
# Issue description

Building with netgen 6.2.2004 I see this error:
```
../src/NETGENPlugin/NETGENPlugin_Mesher.cxx:3058:17: error: 'OCCRefinementSurfaces' is not a member of 'netgen'
         netgen::OCCRefinementSurfaces ref (occgeo);
                 ^~~~~~~~~~~~~~~~~~~~~
../src/NETGENPlugin/NETGENPlugin_Mesher.cxx:3058:17: note: suggested alternative: 'OCCOptimizeSurface'
         netgen::OCCRefinementSurfaces ref (occgeo);
```

**Comment by trelau** [comment]
is netgen 6.2.2004 available on conda-forge or somewhere?

oh i see it's on NGSolve channel, but not conda-forge yet. is SMESH on conda-forge using netgen from NGSolve? i would ave assumed it was using conda-forge.

**Comment by looooo** [comment]
No it's using netgen from conda-forge but I wanted to update netgen...

**Comment by looooo** [comment]
Also rerunning the windows build on azure fails with:
```
OpUtil.cxx.obj : error LNK2001: unresolved external symbol __imp_gethostname
```

**Comment by looooo** [comment]
Trying to solve the netgen 6.2.2004 issue with this patch:

```
diff --git a/src/NETGENPlugin/NETGENPlugin_Mesher.cxx b/src/NETGENPlugin/NETGENPlugin_Mesher.cxx
index 24ffc26..e9daff9 100644
--- a/src/NETGENPlugin/NETGENPlugin_Mesher.cxx
+++ b/src/NETGENPlugin/NETGENPlugin_Mesher.cxx
@@ -74,6 +74,7 @@
 #endif
 #include <occgeom.hpp>
 #include <meshing.hpp>
+#include <nglib.h>
 //#include <ngexception.hpp>
 namespace netgen {
 #if NETGEN_VERSION >= NETGEN_VERSION_STRING(6,2)
@@ -3055,8 +3056,10 @@ bool NETGENPlugin_Mesher::Compute()
           _ngMesh->Compress();
         }
         // convert to quadratic
-        netgen::OCCRefinementSurfaces ref (occgeo);
-        ref.MakeSecondOrder (*_ngMesh);
+        // netgen::OCCRefinementSurfaces ref (occgeo);
+        // ref.MakeSecondOrder (*_ngMesh);
+
+        nglib::Ng_OCC_Generate_SecondOrder(occgeo, _ngMesh)
 
         // care of elements already loaded to SMESH
         // if ( initState._nbSegments > 0 )
```

but no luck:

```
 error: 'Ng_OCC_Generate_SecondOrder' is not a member of 'nglib'
```

**Comment by looooo** [comment]
I managed to build with netgen 6.2.2004 but there is still a runtime error when trying to launch freecad. Not sure if freecad needs to be rebuid.
```
/home/lo/miniconda3/envs/freecad/lib/./libNETGENPlugin.so.8.3: undefined symbol: _ZN6netgen15OCCGenerateMeshERNS_11OCCGeometryERSt10shared_ptrINS_4MeshEERNS_17MeshingParametersE
```

**Comment by looooo** [comment]
It seems like we need to rework the OCCGenerateMesh function. It's now done like this:
```
geo->SetOCCParameters(occparam);
auto mesh = make_shared<Mesh>();
geo->GenerateMesh(mesh, mp);
mesh->SetGeometry(geo);
SetGlobalMesh(mesh);
```

**Comment by hobbes1069** [comment]
Trying to update smesh for Fedora and running into this:

```
In file included from /builddir/build/BUILD/SMESH-8.3.0.3/inc/NETGENPlugin_Mesher.hxx:44,
                 from /builddir/build/BUILD/SMESH-8.3.0.3/src/NETGENPlugin/NETGENPlugin_Mesher.cxx:30:
/usr/include/netgen-mesher/nglib.h:34: note: this is the location of the previous definition
   34 |   #define DLL_HEADER __attribute__((visibility("default")))
      |
/builddir/build/BUILD/SMESH-8.3.0.3/src/NETGENPlugin/NETGENPlugin_NETGEN_3D.cxx:74:10: fatal error: ngexception.hpp: No such file or directory
   74 | #include <ngexception.hpp>
      |          ^~~~~~~~~~~~~~~~~
```

Fedora has netgen 6.2.2004...

I'm also having a header issue with libmed, but I can file that separately...

**Comment by looooo** [comment]
I removed this line. Not sure if this is causing other issues. Until now I never build successfully with libmed enabled. It would be nice if we can solve this too.

Also have a look here: https://forum.freecadweb.org/viewtopic.php?f=42&t=45709

And please report about any progress. I feel quite lost with this issue.

**Comment by hobbes1069** [comment]
Ok, after removing the line I get to here:

```
builddir/build/BUILD/SMESH-8.3.0.3/src/NETGENPlugin/NETGENPlugin_Mesher.cxx:3058:17: error: 'OCCRefinementSurfaces' is not a member of 'netgen'
 3058 |         netgen::OCCRefinementSurfaces ref (occgeo);
      |                 ^~~~~~~~~~~~~~~~~~~~~
/builddir/build/BUILD/SMESH-8.3.0.3/src/NETGENPlugin/NETGENPlugin_Mesher.cxx:3059:13: error: overloaded function with no contextual type information
 3059 |         ref.MakeSecondOrder (*_ngMesh);
      |             ^~~~~~~~~~~~~~~
```

**Comment by looooo** [comment]
see my PR, but this is WIP #21

**Comment by hobbes1069** [comment]
Never mind, just found your pull request. Used it as a patch...

**Comment by hobbes1069** [comment]
Ok, I've been working on this WAY to much this morning but I kicked off a scratch build for Fedora if you want to look at the errors and compare to what you're seeing:

https://koji.fedoraproject.org/koji/taskinfo?taskID=44119545

**Comment by looooo** [comment]
@hobbes1069 I am working on this since 3 days, without much progress... ; ) Anyway, I was able to create a mesh in freecad. But on every second mesh-operation freecad crashes. Maybe someone is able to debug this. I don't have a debug-build of freecad available.

**Comment by hobbes1069** [comment]
If you can install Fedora on something I can create debug builds to test with.

**Comment by trelau** [comment]
while you're here, i'd be interested in feedback on https://github.com/LaughlinResearch/SMESH/issues/16. I'm getting closer to taking that on (got pyOCCT going for OCCT 7.4.0 and SMESH 8.3.0.3 for linux/windows py3.6-3.8).

i'm leaning towards making this SMESH repo and project that clones the Salome repos and then patches everything up on the fly to build the standalone SMESH. Hopefully making it more automatic to stay up to date with Salome SMESH. That means the the existing sources and things would go away, and what would be maintained in this repo is the build/CI process and patches (whether that's done by cmake or just something like a python script tbd). just curious if that seems like a good way to move forward for this project and downstream users. ultimately you would end up with conda packages in the same way, just not a repo of .hxx and .cxx source files to maintain and look at, i suppose.

**Comment by hobbes1069** [comment]
I think that would be good for CI, but I still need archives for distro packaging purposes.

**Comment by looooo** [comment]
@trelau not sure if updating smesh makes a lot of sense for netgen 6.2.2004 support. Normally they (salome smesh) are behind us with netgen support. At least this was the case with netgen 6.2.1808. I think there is not too much missing for netgen6.2.2004.

**Comment by trelau** [comment]
@looooo i was just curious for input in general. i would still want to patch up smesh 9.3 to work with latest netgen, like this current repo. can carry on the conversation on that ticket if you're intereseted, otherwie, ndb.

**Comment by trelau** [comment]
Addressed in https://github.com/trelau/SMESH/pull/31. tl;dr this project will drop support for Netgen v6 and just use 5.3 to be consistent with upstream Salome sources. The meshing benefits in the later versions are not obvious and the API seems to be changing so much that supporting it doesn't seem worth it.
