### ISSUE TITLE
8.3.0.3 does not build with med 4.0.0 on Fedora Rawhide

### ISSUE THREAD

**Issue by hobbes1069** [trelau/SMESH#22]
```
n file included from /builddir/build/BUILD/SMESH-8.3.0.3/src/DriverMED/DriverMED_Family.cxx:28:
/builddir/build/BUILD/SMESH-8.3.0.3/inc/DriverMED_Family.h:37:10: fatal error: MED_Common.hxx: No such file or directory
   37 | #include "MED_Common.hxx"
      |          ^~~~~~~~~~~~~~~~
```

MED_Common.hxx does not exist in med 4.0.0, at least in the archive. I don't suppose it could be a generated header?

**Comment by trelau** [comment]
MED is currently not supported and recent worked updated to SMESH 9.6.0. Is this issue still relevant or can it be closed?

**Comment by hobbes1069** [comment]
This I guess this can be closed. Will 9.6.0 be released soon?

**Comment by trelau** [comment]
there is some work to be done updating the conda-forge feedstock, and then i suspect a new release will be cut
